######################### PRODUCTS ROUTES #########################

### GET all products // ok
GET http://localhost:9000/products/

### GET a specific product based on its ref // ok
GET http://localhost:9000/products/0


### CREATE a product //ok
Post http://localhost:9000/products/add-product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJuYW1lIjoidGVzdDFBZG1pbiIsImVtYWlsIjoidGVzdDFBZG1pbkB0ZXN0LmNvbSIsImlhdCI6MTY5Mjk2NTE5MiwiZXhwIjoxNjkzMjI0MzkyfQ.1zcNJ4Mhw22xnf3ehYxIDvccoEADsEsDJ8dHgCripXQ


{
    "reference": 2123,
    "name": "testi Loremm Ipsum", 
    "description": "Lorem ipsuuuuum",
    "price": 65.99,
    "image" : "https://i.pinimg.com/736x/9e/3f/5a/9e3f5a9ee345f387aaaff715faa11864.jpg"
}

### DELETE a specific product based on its ref // ok
DELETE http://localhost:9000/products/2123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJuYW1lIjoidGVzdDFBZG1pbiIsImVtYWlsIjoidGVzdDFBZG1pbkB0ZXN0LmNvbSIsImlhdCI6MTY5Mjk2NTE5MiwiZXhwIjoxNjkzMjI0MzkyfQ.1zcNJ4Mhw22xnf3ehYxIDvccoEADsEsDJ8dHgCripXQ


### UPDATE a specific product 
PATCH http://localhost:9000/products/1923
Content-Type: application/json

{
    "name" : "XXX",
    "description" : "XXX"
}

######################### Carts ROUTES #########################

### CREATE a new cart
POST http://localhost:9000/cart/order
??? 

### GET all carts
GET http://localhost:9000/cart

### CREATE a new cart
POST http://localhost:9000/cart/order/checkout
??? 



######################### Authorization ROUTES #########################

### REGISTER Route
POST http://localhost:9000/register/admin
Content-Type: application/json

{
    "name" : "test1Admin",
    "email": "test1Admin@test.com",
    "password" : "test3"
}


### LOGIN Route
POST http://localhost:9000/login/admin
Content-Type: application/json

{
    "email" : "test1Admin@test.com",
    "password" : "test3"
}
