######################### PRODUCTS ROUTES #########################

### GET all products // ok
GET http://localhost:9000/products/

### GET a specific product based on its ref // ok
GET http://localhost:9000/products/0


### CREATE a product //ok
Post http://localhost:9000/products/add-product
Content-Type: application/json

{
    "reference": 1123,
    "name": "Gloves Lorem Ipsum", 
    "description": "Lorem ipsum",
    "price": 65.99,
    "image" : "https://i.pinimg.com/736x/9e/3f/5a/9e3f5a9ee345f387aaaff715faa11864.jpg"
}

### DELETE a specific product based on its ref // ok
DELETE http://localhost:9000/products/2000


### UPDATE a specific product 
PATCH http://localhost:9000/products/333
Content-Type: application/json

{
    "name" : "XXX",
    "description" : "XXX"
}

######################### Carts ROUTES #########################

### GET all carts
http://localhost:9000/cart

######################### Authorization ROUTES #########################

### LOGIN Route
GET http://localhost:9000/login

### REGISTER Route
POST http://localhost:9000/register
Content-Type: application/json

{
    "name" : "test",
    "email": "test@test.com",
    "password" : "test"
}